# Generated by Django 6.0.2 on 2026-03-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LAWYER', 'Lawyer'), ('JUDGE', 'Judge'), ('CLERK', 'Court Clerk'), ('REGISTRAR', 'Registrar'), ('DEFENDANT', 'Defendant'), ('CITIZEN', 'Citizen')], db_index=True, default='CITIZEN', max_length=20),
        ),
    ]
