# Generated by Django 6.0.2 on 2026-03-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at_user_is_deleted_user_last_login_ip_and_more'),
        ('accounts', '0003_user_deleted_at_user_is_deleted_user_last_login_ip_and_more'),
    ]

    operations = [
    ]
