# Generated by Django 6.0.4 on 2026-04-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LAWYER', 'Lawyer'), ('JUDGE', 'Judge'), ('CLERK', 'Court Clerk'), ('REGISTRAR', 'Registrar'), ('DEFENDANT', 'Defendant'), ('CITIZEN', 'Citizen')], db_index=True, default='CITIZEN', max_length=20),
        ),
    ]
