# Generated by Django 5.0.6 on 2026-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_last_login_ip_remove_user_login_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(default='Hawassa City', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='address_kebele',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_region',
            field=models.CharField(default='Sidama', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='address_subcity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
    ]
