# Generated by Django 6.0.2 on 2026-05-26 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in international format: '+999999999'. Up to 15 digits allowed.", regex='^\\+\\d{9,15}$')]),
        ),
    ]
