# Generated by Django 6.0.2 on 2026-05-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
        ('accounts', '0009_alter_user_phone_number'),
    ]

    operations = [
    ]
