# Generated by Django 6.0.2 on 2026-03-08 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('main_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cases_case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cases_casecategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'decisions_decision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('scheduled_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'hearings_hearing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('assigned_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cases_judgeassignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'payments_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('system_overview', 'System Overview'), ('judge_report', 'Judge Report'), ('financial_report', 'Financial Report'), ('case_status_report', 'Case Status Report'), ('case_distribution_report', 'Case Distribution Report'), ('performance_report', 'Performance Report'), ('case_intelligence_report', 'Case Intelligence Report')], max_length=50)),
                ('report_category', models.CharField(choices=[('system_report', 'System Report'), ('judge_report', 'Judge Report'), ('financial_report', 'Financial Report'), ('analytics_report', 'Analytics Report'), ('performance_report', 'Performance Report')], max_length=50)),
                ('generated_for_role', models.CharField(max_length=50)),
                ('report_period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom_range', 'Custom Range'), ('last_x_days', 'Last X Days')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_parameter', models.IntegerField(blank=True, null=True)),
                ('case_type', models.CharField(blank=True, max_length=100, null=True)),
                ('case_status', models.CharField(blank=True, max_length=50, null=True)),
                ('file_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('total_cases', models.IntegerField(default=0)),
                ('resolved_cases', models.IntegerField(default=0)),
                ('pending_cases', models.IntegerField(default=0)),
                ('rejected_cases', models.IntegerField(default=0)),
                ('closed_cases', models.IntegerField(default=0)),
                ('average_resolution_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_resolution_days', models.IntegerField(blank=True, null=True)),
                ('maximum_resolution_days', models.IntegerField(blank=True, null=True)),
                ('hearings_conducted', models.IntegerField(default=0)),
                ('decisions_written', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('judge_service_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid_cases', models.IntegerField(default=0)),
                ('unpaid_cases', models.IntegerField(default=0)),
                ('cases_per_judge', models.JSONField(blank=True, null=True)),
                ('cases_per_registrar', models.JSONField(blank=True, null=True)),
                ('average_case_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('backlog_cases', models.IntegerField(default=0)),
                ('most_common_case_type', models.CharField(blank=True, max_length=100, null=True)),
                ('most_common_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('top_issues', models.JSONField(blank=True, null=True)),
                ('education_distribution', models.JSONField(blank=True, null=True)),
                ('gender_distribution', models.JSONField(blank=True, null=True)),
                ('age_group_distribution', models.JSONField(blank=True, null=True)),
                ('occupation_distribution', models.JSONField(blank=True, null=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_duration_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('report_summary', models.TextField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_specific_reports', to=settings.AUTH_USER_MODEL)),
                ('registrar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
