# Generated by Django 6.0.2 on 2026-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingParticipant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hearings_hearingparticipant',
                'managed': False,
            },
        ),
    ]
