# Generated by Django 6.0.2 on 2026-03-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('CASE_SUBMITTED', 'Case Submitted'), ('CASE_ACCEPTED', 'Case Accepted'), ('CASE_REJECTED', 'Case Rejected'), ('JUDGE_ASSIGNED', 'Judge Assigned'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('HEARING_REMINDER', 'Hearing Reminder'), ('HEARING_CANCELLED', 'Hearing Cancelled'), ('DECISION_ISSUED', 'Decision Issued'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('ACTION_REQUIRED', 'Action Required'), ('SYSTEM_ALERT', 'System Alert')], max_length=30),
        ),
    ]
