# Generated by Django 6.0.2 on 2026-05-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='sms_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
