services:
  - type: web
    name: justicehub-backend
    env: python
    buildCommand: "sh ./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: justicehub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: FRONTEND_URL
        value: "https://justicehub-frontend.onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: web
    name: justicehub-frontend
    env: node
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://justicehub-backend.onrender.com/api"

databases:
  - name: justicehub-db
    databaseName: justicehub
    user: justicehub_user
    plan: free
