# Generated by Django 6.0.2 on 2026-02-28 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('OTP_VERIFIED', 'OTP Verified'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('ROLE_CHANGED', 'Role Changed'), ('CASE_CREATED', 'Case Created'), ('CASE_UPDATED', 'Case Updated'), ('CASE_DELETED', 'Case Deleted'), ('CASE_VIEWED', 'Case Viewed'), ('CASE_ACCEPTED', 'Case Accepted'), ('CASE_REJECTED', 'Case Rejected'), ('CASE_ASSIGNED', 'Case Assigned'), ('CASE_STATUS_CHANGED', 'Case Status Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('DOCUMENT_DELETED', 'Document Deleted'), ('DOCUMENT_UPDATED', 'Document Updated'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('HEARING_UPDATED', 'Hearing Updated'), ('HEARING_CANCELLED', 'Hearing Cancelled'), ('HEARING_COMPLETED', 'Hearing Completed'), ('HEARING_ATTENDANCE', 'Hearing Attendance'), ('DECISION_CREATED', 'Decision Created'), ('DECISION_UPDATED', 'Decision Updated'), ('DECISION_PUBLISHED', 'Decision Published'), ('DECISION_VIEWED', 'Decision Viewed'), ('DECISION_DOWNLOADED', 'Decision Downloaded'), ('API_ACCESS', 'API Access'), ('EXPORT_DATA', 'Export Data'), ('REPORT_GENERATED', 'Report Generated'), ('SETTINGS_CHANGED', 'Settings Changed'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_RESTORED', 'Backup Restored')], max_length=50)),
                ('action_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked')], default='SUCCESS', max_length=20)),
                ('description', models.TextField()),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='audit_logs__model_n_8b4c57_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='audit_logs__user_id_5d4364_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='audit_logs__action__aba482_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='useractionlog',
            name='user',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs__timesta_aec53a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type'], name='audit_logs__action__6cd600_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs__user_id_d7ae1d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_logs__content_9ccfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_status'], name='audit_logs__action__3490d6_idx'),
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
