# Generated by Django 5.0.6 on 2026-04-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('OTP_VERIFIED', 'OTP Verified'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('ROLE_CHANGED', 'Role Changed'), ('CASE_CREATED', 'Case Created'), ('CASE_UPDATED', 'Case Updated'), ('CASE_DELETED', 'Case Deleted'), ('CASE_VIEWED', 'Case Viewed'), ('CASE_ACCEPTED', 'Case Accepted'), ('CASE_REJECTED', 'Case Rejected'), ('CASE_ASSIGNED', 'Case Assigned'), ('CASE_STATUS_CHANGED', 'Case Status Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('DOCUMENT_DOWNLOADED', 'Document Downloaded'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('DOCUMENT_DELETED', 'Document Deleted'), ('DOCUMENT_UPDATED', 'Document Updated'), ('HEARING_SCHEDULED', 'Hearing Scheduled'), ('HEARING_UPDATED', 'Hearing Updated'), ('HEARING_CANCELLED', 'Hearing Cancelled'), ('HEARING_COMPLETED', 'Hearing Completed'), ('HEARING_ATTENDANCE', 'Hearing Attendance'), ('DECISION_CREATED', 'Decision Created'), ('DECISION_UPDATED', 'Decision Updated'), ('DECISION_PUBLISHED', 'Decision Published'), ('DECISION_VIEWED', 'Decision Viewed'), ('DECISION_DOWNLOADED', 'Decision Downloaded'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('API_ACCESS', 'API Access'), ('EXPORT_DATA', 'Export Data'), ('REPORT_GENERATED', 'Report Generated'), ('SETTINGS_CHANGED', 'Settings Changed'), ('BACKUP_CREATED', 'Backup Created'), ('BACKUP_RESTORED', 'Backup Restored')], max_length=50),
        ),
    ]
