# Generated by Django 5.0.6 on 2026-04-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_suspicious',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
