# Generated by Django 6.0.2 on 2026-02-23 18:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('hearing_type', models.CharField(choices=[('INITIAL', 'Initial Hearing'), ('STATUS', 'Status Conference'), ('EVIDENTIARY', 'Evidentiary Hearing'), ('MOTION', 'Motion Hearing'), ('TRIAL', 'Trial'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(15)])),
                ('location', models.CharField(max_length=255)),
                ('virtual_meeting_link', models.URLField(blank=True, null=True)),
                ('agenda', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('transcript_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presiding_hearings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='HearingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_hearing', models.CharField(max_length=50)),
                ('attendance_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_list', to='hearings.hearing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hearing', 'role_in_hearing'],
                'unique_together': {('hearing', 'user')},
            },
        ),
        migrations.AddField(
            model_name='hearing',
            name='participants',
            field=models.ManyToManyField(related_name='hearings_participated', through='hearings.HearingParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HearingReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='hearings.hearing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['case', 'scheduled_date'], name='hearings_he_case_id_b4d27b_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['judge', 'scheduled_date'], name='hearings_he_judge_i_e7f604_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['status'], name='hearings_he_status_7ee3fd_idx'),
        ),
    ]
