# Generated by Django 6.0.2 on 2026-03-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0002_hearing_deleted_at_hearing_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='hearing_format',
            field=models.CharField(choices=[('PHYSICAL', 'Physical Hearing'), ('VIRTUAL', 'Virtual Hearing')], default='PHYSICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='hearingparticipant',
            name='confirmation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='hearingparticipant',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='hearingparticipant',
            name='attendance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PENDING', max_length=20),
        ),
    ]
