# Generated by Django 6.0.2 on 2026-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0003_hearing_cancellation_reason_hearing_hearing_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='hearing_number',
            field=models.IntegerField(blank=True, help_text='Sequence number of the hearing for this case', null=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='hearing_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Hearing'), ('INTRO', 'Case Introduction'), ('EVIDENCE', 'Evidence Hearing'), ('WITNESS', 'Witness Hearing'), ('ARGUMENT', 'Argument Hearing'), ('FINAL', 'Final Hearing'), ('FINAL_ARGUMENT', 'Final Argument'), ('JUDGMENT', 'Judgment'), ('STATUS', 'Status Conference'), ('EVIDENTIARY', 'Evidentiary Hearing'), ('MOTION', 'Motion Hearing'), ('TRIAL', 'Trial'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
