# Generated by Django 6.0.2 on 2026-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0004_hearing_hearing_number_alter_hearing_hearing_type'),
    ]

    def convert_notes_to_json(apps, schema_editor):
        import json
        Hearing = apps.get_model('hearings', 'Hearing')
        for hearing in Hearing.objects.all():
            if hearing.notes and isinstance(hearing.notes, str):
                try:
                    # Check if it's already valid JSON
                    json.loads(hearing.notes)
                except (ValueError, TypeError):
                    # If not, wrap it in a dict and dump to JSON string
                    hearing.notes = json.dumps({"summary": hearing.notes})
                    hearing.save()

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='conducted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='minutes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(convert_notes_to_json),
        migrations.AlterField(
            model_name='hearing',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('CONDUCTED', 'Conducted'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
    ]
