# Generated by Django 6.0.2 on 2026-04-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0005_hearing_conducted_at_hearing_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='transcript_url',
        ),
        migrations.AddField(
            model_name='hearing',
            name='action',
            field=models.CharField(blank=True, choices=[('RESOLVED', 'Resolved'), ('POSTPONED', 'Postponed'), ('CONTINUED', 'Continued'), ('ADJOURNED', 'Adjourned')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='judge_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='next_hearing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='previous_hearing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_hearings', to='hearings.hearing'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
