# Generated by Django 6.0.2 on 2026-02-23 18:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('decision_type', models.CharField(choices=[('INTERIM', 'Interim Order'), ('FINAL', 'Final Judgment'), ('DISMISSAL', 'Dismissal'), ('SETTLEMENT', 'Settlement Approval'), ('OTHER', 'Other')], max_length=20)),
                ('decision_number', models.CharField(max_length=50, unique=True)),
                ('introduction', models.TextField()),
                ('background', models.TextField()),
                ('analysis', models.TextField()),
                ('conclusion', models.TextField()),
                ('order', models.TextField(help_text='The final order/ruling')),
                ('laws_cited', models.TextField(blank=True, null=True)),
                ('cases_cited', models.TextField(blank=True, null=True)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='decisions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='cases.case')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_publish_decision', 'Can publish decision')],
            },
        ),
        migrations.CreateModel(
            name='DecisionDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('EMAIL', 'Email'), ('PERSONAL', 'Personal Service'), ('POST', 'Postal Mail'), ('PORTAL', 'Online Portal')], max_length=20)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='decisions.decision')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['decision_number'], name='decisions_d_decisio_20cb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['case', '-created_at'], name='decisions_d_case_id_3c8305_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['judge', '-created_at'], name='decisions_d_judge_i_e6d4c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='decisiondelivery',
            unique_together={('decision', 'recipient')},
        ),
    ]
