# Generated by Django 6.0.2 on 2026-02-28 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_useractionlog_cases_usera_user_id_0b3c39_idx_and_more'),
        ('decisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reasons', models.TextField()),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-filed_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
                ('background', models.TextField()),
                ('analysis', models.TextField()),
                ('conclusion', models.TextField()),
                ('order', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_decision', 'Can publish decision'), ('can_finalize_decision', 'Can finalize decision')]},
        ),
        migrations.AddField(
            model_name='decision',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='decision',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='decision',
            name='decision_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['status'], name='decisions_d_status_d77b8a_idx'),
        ),
        migrations.AddField(
            model_name='decisionappeal',
            name='appellant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionappeal',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='decisioncomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisioncomment',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='decisionversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionversion',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='decisions.decision'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionversion',
            unique_together={('decision', 'version')},
        ),
    ]
