# Generated by Django 6.0.2 on 2026-03-13 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casedocumentversion_and_more'),
        ('decisions', '0002_decisionappeal_decisioncomment_decisionversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_uploaded', to='cases.casedocument'),
        ),
    ]
