# Generated by Django 6.0.2 on 2026-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_decision_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decision',
            name='immediate_reason',
            field=models.CharField(blank=True, choices=[('MEDIATED', 'Solved by mediated'), ('WITHDRAWN', 'Withdrawn by the plaintiff')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='decision_type',
            field=models.CharField(choices=[('INTERIM', 'Interim Order'), ('FINAL', 'Final Judgment'), ('DISMISSAL', 'Dismissal'), ('SETTLEMENT', 'Settlement Approval'), ('IMMEDIATE', 'Immediate Decision'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='decision',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='order',
            field=models.TextField(blank=True, help_text='The final order/ruling', null=True),
        ),
    ]
