# Generated by Django 6.0.2 on 2026-04-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0004_decision_description_decision_finalized_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionAppeal',
        ),
    ]
