# Generated by Django 6.0.2 on 2026-02-23 18:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Case Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(help_text='Category code (e.g., CIV-001)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Case Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='cases_casec_code_cdbd50_idx'), models.Index(fields=['is_active'], name='cases_casec_is_acti_2e8f7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('case_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], db_index=True, default='PENDING_REVIEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('file_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('court_name', models.CharField(blank=True, max_length=200, null=True)),
                ('court_room', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('filing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('defendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_as_defendant', to=settings.AUTH_USER_MODEL)),
                ('defendant_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defendant_cases', to=settings.AUTH_USER_MODEL)),
                ('plaintiff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_as_plaintiff', to=settings.AUTH_USER_MODEL)),
                ('plaintiff_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintiff_cases', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casecategory')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_assign_judge', 'Can assign judge to case'), ('can_review_case', 'Can review case'), ('can_manage_documents', 'Can manage case documents')],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=10)),
                ('document_type', models.CharField(choices=[('PETITION', 'Petition'), ('EVIDENCE', 'Evidence'), ('AFFIDAVIT', 'Affidavit'), ('ORDER', 'Court Order'), ('JUDGMENT', 'Judgment'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case')),
            ],
            options={
                'verbose_name_plural': 'Case Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='cases.case')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_active_cases', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bar_certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specializations', models.ManyToManyField(related_name='judges', to='cases.casecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Judge Profile',
                'verbose_name_plural': 'Judge Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['file_number'], name='cases_case_file_nu_0c76c9_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'created_at'], name='cases_case_status_3a818e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_by', 'status'], name='cases_case_created_993a92_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='cases_case_priorit_474e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['plaintiff', 'defendant'], name='cases_case_plainti_63b3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['case', 'document_type'], name='cases_cased_case_id_f9271c_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['uploaded_by', 'uploaded_at'], name='cases_cased_uploade_fb69cf_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['judge', 'is_active'], name='cases_judge_judge_i_35ed0a_idx'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['case', 'is_active'], name='cases_judge_case_id_d6bda2_idx'),
        ),
        migrations.AddConstraint(
            model_name='judgeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('case', 'is_active'), name='unique_active_assignment_per_case'),
        ),
        migrations.AddIndex(
            model_name='useractionlog',
            index=models.Index(fields=['user', '-created_at'], name='cases_usera_user_id_0b3c39_idx'),
        ),
        migrations.AddIndex(
            model_name='useractionlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='cases_usera_entity__c444be_idx'),
        ),
    ]
