# Generated by Django 6.0.2 on 2026-02-27 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='checksum',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='casedocument',
            constraint=models.UniqueConstraint(fields=('case', 'checksum'), name='unique_checksum_per_case'),
        ),
    ]
