# Generated by Django 6.0.2 on 2026-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_casedocument_checksum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecategory',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Required fee for this category', max_digits=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], db_index=True, default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='name',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], max_length=20, unique=True),
        ),
    ]
