# Generated by Django 6.0.2 on 2026-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_casecategory_fee_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
