# Generated by Django 6.0.2 on 2026-02-28 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_deleted_at_case_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='cases_usera_user_id_0b3c39_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractionlog',
            name='cases_usera_entity__c444be_idx',
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['category'], name='cases_case_categor_4c508b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='cases_case_created_a9dee7_idx'),
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
