# Generated by Django 6.0.2 on 2026-03-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_remove_useractionlog_cases_usera_user_id_0b3c39_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="defendant_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
