# Generated by Django 6.0.2 on 2026-03-04 19:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_useractionlog_cases_usera_user_id_0b3c39_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=10)),
                ('checksum', models.CharField(max_length=64)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='casedocument',
            name='unique_checksum_per_case',
        ),
        migrations.AddField(
            model_name='casedocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casedocumentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cases.casedocument'),
        ),
        migrations.AddField(
            model_name='casedocumentversion',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='file_type',
        ),
        migrations.AddIndex(
            model_name='casedocumentversion',
            index=models.Index(fields=['document', 'version_number'], name='cases_cased_documen_e8d7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocumentversion',
            index=models.Index(fields=['status'], name='cases_cased_status_9a50c9_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocumentversion',
            index=models.Index(fields=['is_active'], name='cases_cased_is_acti_30da2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casedocumentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
