# Generated by Django 6.0.2 on 2026-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casedocumentversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('DECIDED', 'Decided'), ('CLOSED', 'Closed')], db_index=True, default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='name',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('DECIDED', 'Decided'), ('CLOSED', 'Closed')], max_length=20, unique=True),
        ),
    ]
