# Generated by Django 6.0.2 on 2026-03-15 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_status_alter_casestatus_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='document_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the document', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='signature_algorithm',
            field=models.CharField(default='RSA-SHA256', max_length=50),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='signature_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
