# Generated by Django 6.0.2 on 2026-03-18 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_casedocument_digital_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeprofile',
            name='max_active_cases',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
