# Generated by Django 6.0.2 on 2026-03-18 06:16

from django.db import migrations

def update_judge_limits(apps, schema_editor):
    JudgeProfile = apps.get_model('cases', 'JudgeProfile')
    JudgeProfile.objects.all().update(max_active_cases=10)

def reverse_update_judge_limits(apps, schema_editor):
    JudgeProfile = apps.get_model('cases', 'JudgeProfile')
    # Reverting to previous default (3)
    JudgeProfile.objects.all().update(max_active_cases=3)

class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_judgeprofile_max_active_cases'),
    ]

    operations = [
        migrations.RunPython(update_judge_limits, reverse_update_judge_limits),
    ]
