# Generated by Django 6.0.2 on 2026-03-20 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_auto_20260318_0916'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid')], db_index=True, default='NOT_PAID', max_length=20),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['payment_status'], name='cases_case_payment_ee3c80_idx'),
        ),
    ]
