# Generated by Django 6.0.2 on 2026-03-27 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_case_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_defendant_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casecategory',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casecategory',
            name='is_defendant_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='is_defendant_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casenotes',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casenotes',
            name='is_defendant_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judgeprofile',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judgeprofile',
            name='is_defendant_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CaseActionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_description', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='cases.case')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Action Request',
                'verbose_name_plural': 'Case Action Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
