# Generated by Django 6.0.2 on 2026-04-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_defendant_name'),
        ('cases', '0012_case_acknowledged_at_case_is_defendant_acknowledged_and_more'),
    ]

    operations = [
    ]
