# Generated by Django 6.0.2 on 2026-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_merge_20260408_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='defendant_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
