# Generated by Django 5.0.6 on 2026-04-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_case_defendant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeprofile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_LEAVE', 'On Leave')], db_index=True, default='AVAILABLE', max_length=20),
        ),
    ]
