# Generated by Django 5.0.6 on 2026-04-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_judgeprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='has_defendant_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cases.casecategory'),
        ),
    ]
