# Generated by Django 5.0.6 on 2026-05-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_case_has_defendant_responded_case_responded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecategory',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='casecategory',
            name='is_defendant_acknowledged',
        ),
        migrations.RemoveField(
            model_name='casecategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='is_defendant_acknowledged',
        ),
        migrations.RemoveField(
            model_name='casenotes',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='casenotes',
            name='is_defendant_acknowledged',
        ),
        migrations.RemoveField(
            model_name='judgeprofile',
            name='acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='judgeprofile',
            name='is_defendant_acknowledged',
        ),
    ]
