# Generated by Django 5.0.6 on 2026-05-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_remove_casecategory_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseStatus',
        ),
    ]
