# Generated by Django 5.0.6 on 2026-05-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_delete_casestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='defendant_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='defendant_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
